{!! do_shortcode('[banner]') !!}
{!! do_shortcode('[popular-destination]') !!}
{!! do_shortcode('[cta-card]') !!}
{!! do_shortcode('[recommend]') !!}
{!! do_shortcode('[features]') !!}
{!! do_shortcode('[testimonials]') !!}
{!! do_shortcode('[blog-card]') !!}
{!! do_shortcode('[filter-destination]') !!}
{!! do_shortcode('[newsletter]') !!}
